### ISSUE TITLE
Mild issues throughout the site.

### ISSUE THREAD

**Issue by BraxtonMDevelops** [undefinedDarkness/undefineddarkness.github.io#1]
On the about.md page https://github.com/undefinedDarkess is broken. You're missing an "n" .

No header for flycheck/linting section on emacs blogpost 
No close quote on emacs blogpost. 

These are all very mild things.  Just stuff you may want to fix.  Overall the blogpost was very enjoyable to read, not least because one of my favorite fonts, Recursive, was being shown off.

**Comment by davidnoronha1** [comment]
I'll work on fixing them, Glad you liked it
